# Generated by Django 2.1.3 on 2018-11-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board_menu',
            name='b_order',
            field=models.IntegerField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
