# Generated by Django 2.1.3 on 2018-11-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_board_menu_b_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='board_menu',
            name='b_descript',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='board_menu',
            name='b_order',
            field=models.IntegerField(),
        ),
    ]
