# Generated by Django 2.1.3 on 2018-11-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20181114_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='b_short_intro',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
