# Generated by Django 2.1.3 on 2018-11-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_boards_b_short_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='b_short_intro',
            field=models.CharField(max_length=100),
        ),
    ]
