# Generated by Django 2.1.3 on 2018-11-15 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20181115_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='b_type',
        ),
    ]
