# Generated by Django 2.1.3 on 2018-11-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_remove_file_b_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='f_file',
            field=models.FileField(upload_to='pages/upload/'),
        ),
    ]
